# Generated by Django 5.0.1 on 2024-06-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0002_alter_user_options_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
