# Generated by Django 5.0.1 on 2024-06-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0003_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', max_length=255, upload_to=''),
        ),
    ]
