# Generated by Django 5.0.1 on 2024-06-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0006_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
