# Generated by Django 5.0.1 on 2024-06-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0008_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
