# Generated by Django 5.0.1 on 2024-09-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0011_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RenameField(
            model_name='records',
            old_name='trials',
            new_name='trial',
        ),
        migrations.AddField(
            model_name='records',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
