# Generated by Django 5.0.1 on 2024-09-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0012_alter_event_options_rename_trials_records_trial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='records',
            name='graph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
