# Generated by Django 5.0.1 on 2024-09-27 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0013_alter_records_options_records_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='graph',
        ),
    ]
