# Generated by Django 5.0.1 on 2024-09-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0014_remove_records_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='note',
        ),
        migrations.AddField(
            model_name='records',
            name='graph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
