# Generated by Django 5.0.1 on 2024-10-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0016_records_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='address',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='records',
            name='barangay',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='records',
            name='municipality',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='records',
            name='province',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='records',
            name='region',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
