# Generated by Django 5.0.1 on 2024-10-11 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0017_records_address_records_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='barangay',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='records',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='records',
            name='municipality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='records',
            name='province',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='records',
            name='region',
            field=models.CharField(max_length=255),
        ),
    ]
