# Generated by Django 5.0.1 on 2024-10-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0018_alter_records_address_alter_records_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
