# Generated by Django 5.0.1 on 2024-10-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0019_alter_records_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='absorbance',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
