# Generated by Django 5.0.1 on 2024-10-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natrosensor', '0020_records_absorbance'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='concentration',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='records',
            name='absorbance',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
